base='/Users/louk/Data/Raw/Gemi/';

Marker_Translation{1} = { ...
    { '12'              ,            '1'   }    , ...
    { '16'              ,  { '6'  ,  '7'   }  } , ...
    { '20'              ,  { '2'  ,  '3'   }  } , ...
    { '21'              ,  { '4'  ,  '5'   }  } , ...
    { '22'              ,  { '6'  ,  '7'   }  } , ...
    { '23'              ,  { '8'  ,  '9'   }  } , ...
    { '24'              ,  { '10' ,  '11'  }  }   ...
};

Marker_Translation{2} = { ...
    {  { '50' , '51' , '52' , '53' }  ,            '1'   }     , ...
    {  { '15' , '25' , '35' , '45' }  ,  { '2'  ,  '3'   }   } , ...
    {  { '16' , '26' , '36' , '46' }  ,  { '4'  ,  '5'   }   } , ...
    {  { '17' , '27' , '37' , '47' }  ,  { '6'  ,  '7'   }   } , ...
    {  { '18' , '28' , '38' , '48' }  ,  { '8'  ,  '9'   }   } , ...
    {  { '19' , '29' , '39' , '49' }  ,  { '10' ,  '11'  }   } , ...
    };

Subject_To_Group = {...
    
{ 'JPsv02'  ,  'single'    ,  'Japanese'  }, ...               
{ 'JPsv04'  ,  'single'    ,  'Japanese'  }, ...
{ 'JPsv05'  ,  'single'    ,  'Japanese'  }, ...
{ 'JPsv08'  ,  'single'    ,  'Japanese'  }, ...               
{ 'JPsv09'  ,  'single'    ,  'Japanese'  }, ...               
{ 'JPsv11'  ,  'single'    ,  'Japanese'  }, ...               
{ 'JPsv22'  ,  'single'    ,  'Japanese'  }, ...   
...
{ 'JPv02'   ,  'multiple'  ,  'Japanese'  }, ...               
{ 'JPv03'   ,  'multiple'  ,  'Japanese'  }, ...
{ 'JPv04'   ,  'multiple'  ,  'Japanese'  }, ...
{ 'JPv05'   ,  'multiple'  ,  'Japanese'  }, ...               
{ 'JPv07'   ,  'multiple'  ,  'Japanese'  }, ...               
{ 'JPv10'   ,  'multiple'  ,  'Japanese'  }, ...               
{ 'JPv12'   ,  'multiple'  ,  'Japanese'  }, ...   
...
{ 'NLsv01'  ,  'single'    ,  'Dutch'     }, ...               
{ 'NLsv03'  ,  'single'    ,  'Dutch'     }, ...               
{ 'NLsv04'  ,  'single'    ,  'Dutch'     }, ...               
{ 'NLsv05'  ,  'single'    ,  'Dutch'     }, ...               
{ 'NLsv07'  ,  'single'    ,  'Dutch'     }, ...               
{ 'NLsv08'  ,  'single'    ,  'Dutch'     }, ...               
{ 'NLsv09'  ,  'single'    ,  'Dutch'     }, ...               
{ 'NLsv22'  ,  'single'    ,  'Dutch'     }, ...               
{ 'NLsv33'  ,  'single'    ,  'Dutch'     }, ...               
...
{ 'NLv01'   ,  'multiple'  ,  'Dutch'     }, ...               
{ 'NLv03'   ,  'multiple'  ,  'Dutch'     }, ...               
{ 'NLv04'   ,  'multiple'  ,  'Dutch'     }, ...               
{ 'NLv05'   ,  'multiple'  ,  'Dutch'     }, ...               
{ 'NLv06'   ,  'multiple'  ,  'Dutch'     }, ...               
{ 'NLv31'   ,  'multiple'  ,  'Dutch'    }, ...               
...
}; 

