d={'dat' 'is' 'zijn' 'wat leuk!' 'leuk' 'en' 'ook' 'mijn vrouw' 'de moeder[-s]' 'dit' 'dank u'...
    'leuk je te zien' 'zien' 'ga je mee?' 'wat' 'drinken' 'ik ga' 'nu' 'naar huis'...
    };
e={'that' 'from zijn' 'to be' 'how nice' 'nice' 'and' 'too,also' 'mijn vrouw' 'mother' 'this' 'thank you'...
    'nice to see you' 'to see' 'are you coming(along)?' 'something' 'to drink' 'i am going' 'now' 'house'...
    };